import {SkipTransaction} from "../../GenericTypes/Transactions/transaction.ts";

export async function loadTransactions() {

    await new Promise(resolve => setTimeout(resolve, 1000));

    const data: SkipTransaction[] = [
        {
            id: "1",
            userId: "123123",
            userName: "David",
            title: "Diskrete Mathe 2 Lektione",
            reason: "Absoult kei bock meh gha",
            date: new Date(),
            debtValue: 5.0,
            status: 'approved',
            createdByName: 'David',
            createdById: '123123',
            createdAt: "",
            approvedBy: [],
            deletedBy: [],
            requiredApprovals: 2
        },
        {
            id: "2",
            userId: "888999",
            userName: "Luca",
            title: "Analysis Übung",
            reason: "Znacht isch wichtiger gsi 🍝",
            date: new Date(),
            debtValue: 7.5,
            status: 'pending',
            createdByName: 'David',
            createdById: '123123',
            createdAt: "",
            approvedBy: [{id: '123123', name: "asdf"}],
            deletedBy: [{id: '123123', name: "asdf"}],
            requiredApprovals: 2
        },
        {
            id: "2",
            userId: "888999",
            userName: "Luca",
            title: "Analysis Übung",
            reason: "Znacht isch wichtiger gsi 🍝",
            date: new Date(),
            debtValue: 7.5,
            status: 'delete_pending',
            createdByName: 'David',
            createdById: '123123',
            createdAt: "",
            approvedBy: [],
            deletedBy: [],
            requiredApprovals: 2
        },
        {
            id: "2",
            userId: "888999",
            userName: "Luca",
            title: "Analysis Übung",
            reason: "Znacht isch wichtiger gsi 🍝",
            date: new Date(),
            debtValue: 7.5,
            status: 'delete_pending',
            createdByName: 'David',
            createdById: '123123',
            createdAt: "",
            approvedBy: [],
            deletedBy: [],
            requiredApprovals: 2
        },        {
            id: "1",
            userId: "123123",
            userName: "David",
            title: "Diskrete Mathe 2 Lektione",
            reason: "Absoult kei bock meh gha",
            date: new Date(),
            debtValue: 5.0,
            status: 'approved',
            createdByName: 'David',
            createdById: '123123',
            createdAt: "",
            approvedBy: [],
            deletedBy: [],
            requiredApprovals: 2
        },
        {
            id: "2",
            userId: "888999",
            userName: "Luca",
            title: "Analysis Übung",
            reason: "Znacht isch wichtiger gsi 🍝",
            date: new Date(),
            debtValue: 7.5,
            status: 'pending',
            createdByName: 'David',
            createdById: '123123',
            createdAt: "",
            approvedBy: [{id: '123123', name: "asdf"}],
            deletedBy: [{id: '123123', name: "asdf"}],
            requiredApprovals: 2
        },
        {
            id: "2",
            userId: "888999",
            userName: "Luca",
            title: "Analysis Übung",
            reason: "Znacht isch wichtiger gsi 🍝",
            date: new Date(),
            debtValue: 7.5,
            status: 'delete_pending',
            createdByName: 'David',
            createdById: '123123',
            createdAt: "",
            approvedBy: [],
            deletedBy: [],
            requiredApprovals: 2
        },
        {
            id: "2",
            userId: "888999",
            userName: "Luca",
            title: "Analysis Übung",
            reason: "Znacht isch wichtiger gsi 🍝",
            date: new Date(),
            debtValue: 7.5,
            status: 'delete_pending',
            createdByName: 'David',
            createdById: '123123',
            createdAt: "",
            approvedBy: [],
            deletedBy: [],
            requiredApprovals: 2
        },        {
            id: "1",
            userId: "123123",
            userName: "David",
            title: "Diskrete Mathe 2 Lektione",
            reason: "Absoult kei bock meh gha",
            date: new Date(),
            debtValue: 5.0,
            status: 'approved',
            createdByName: 'David',
            createdById: '123123',
            createdAt: "",
            approvedBy: [],
            deletedBy: [],
            requiredApprovals: 2
        },
        {
            id: "2",
            userId: "888999",
            userName: "Luca",
            title: "Analysis Übung",
            reason: "Znacht isch wichtiger gsi 🍝",
            date: new Date(),
            debtValue: 7.5,
            status: 'pending',
            createdByName: 'David',
            createdById: '123123',
            createdAt: "",
            approvedBy: [{id: '123123', name: "asdf"}],
            deletedBy: [{id: '123123', name: "asdf"}],
            requiredApprovals: 2
        },
        {
            id: "2",
            userId: "888999",
            userName: "Luca",
            title: "Analysis Übung",
            reason: "Znacht isch wichtiger gsi 🍝",
            date: new Date(),
            debtValue: 7.5,
            status: 'delete_pending',
            createdByName: 'David',
            createdById: '123123',
            createdAt: "",
            approvedBy: [],
            deletedBy: [],
            requiredApprovals: 2
        },
        {
            id: "2",
            userId: "888999",
            userName: "Luca",
            title: "Analysis Übung",
            reason: "Znacht isch wichtiger gsi 🍝",
            date: new Date(),
            debtValue: 7.5,
            status: 'delete_pending',
            createdByName: 'David',
            createdById: '123123',
            createdAt: "",
            approvedBy: [],
            deletedBy: [],
            requiredApprovals: 2
        },
    ];


    return data;
}